# Generated by Django 6.0.7 on 2026-07-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.IntegerField()),
                ('status', models.CharField(choices=[('CP', 'Completed'), ('NS', 'Not Started'), ('IP', 'In Progress'), ('CA', 'Cancelled')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_data', models.IntegerField()),
                ('status', models.CharField(choices=[('CP', 'Completed'), ('NS', 'Not Started'), ('IP', 'In Progress')], max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.project')),
            ],
        ),
    ]
