# Generated by Django 6.0.7 on 2026-07-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
