# Generated by Django 6.0.7 on 2026-07-22 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='company',
            new_name='company_tasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='project',
            name='company_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(choices=[('G', 'Google'), ('M', 'Microsoft'), ('A', 'Amazon')], max_length=25),
        ),
    ]
