# Generated by Django 6.0.7 on 2026-07-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_company_task_company_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
    ]
