# Generated by Django 6.0.7 on 2026-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('related_object', models.CharField(max_length=30)),
            ],
        ),
    ]
