# Generated by Django 6.0.7 on 2026-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CP', 'Completed'), ('NS', 'Not Started'), ('IP', 'In Progress'), ('CA', 'Cancelled'), ('D', 'Deleted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CP', 'Completed'), ('NS', 'Not Started'), ('IP', 'In Progress'), ('D', 'Deleted')], max_length=2),
        ),
    ]
