# Generated by Django 6.1 on 2026-09-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_room_workspace_alter_project_company_projects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
