# Generated by Django 6.1 on 2026-09-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.workspace'),
            preserve_default=False,
        ),
    ]
